#!/usr/bin/env bash
#script create thea file and stores it PID , displays messages depending on the signal it receives
pgrep -f "$0" > /var/run/myscript.pid
function catchSIGTERM(){
	echo "I hate the kill command"
	TEMPTWO="$(cat /var/run/myscript.pid)"
	rm /var/run/myscript.pid
	kill -9 "$TEMPTWO"
}

function catchSIGINT(){
	echo "Y U no love me?!"
