#!/usr/bin/env bash
#script create thea file and stores it PID , displays messages depending on the signal it receives
echo $$ > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2

	trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT
done
