#!/usr/bin/env bash
#script create thea file and stores it PID , displays messages depending on the signal it receives
pgrep -f "$0" > /var/run/myscript.pid
function catchSIGTERM(){
	echo "I hate the kill command"
	TEMPTWO="$(cat /var/run/myscript.pid)"
	rm /var/run/myscript.pid
	kill -9 "$TEMPTWO"
}

function catchSIGINT(){
	echo "Y U no love me!"#!/usr/bin/env bash
	# Creates the file /var/run/holbertonscript.pid containing its PID
	# Displays 'To infinity and beyond' indefinitely
	# Displays 'I hate the kill command' when receiving a SIGTERM signal
	# Displays 'Y U no love me?!' when receiving a SIGINT signal
	# Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

	sudo touch /var/run/holbertonscript.pid
	sudo bash -c 'echo $$ > /var/run/holbertonscript.pid'
	while true
	do
		    echo "To infinity and beyond"
		        sleep 2
			    trap 'echo "I hate the kill command"; sudo rm /var/run/holbertonscript.pid; exit' SIGTERM
			        trap 'echo "Y U no love me?!"' SIGINT
				    trap 'sudo rm /var/run/holbertonscript.pid; exit' SIGQUIT
			    done
